apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ application }}"
spec:
  rules:
    # DNS name your application should be exposed on
    - host: "{{ application}}.playground.zalan.do"
      http:
        paths:
          - backend:
              serviceName: "{{ application }}"
              servicePort: 80
