apiVersion: v1
kind: Service
metadata:
  labels:
    application: "{{ application }}"
  name: "{{ application }}"
spec:
  selector:
    application: "{{ application }}"
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      # this needs to match your container port
      targetPort: 8080
