apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ application }}-{{ version }}-{{ release }}"
spec:
  replicas: {{ replicas }}
  template:
    metadata:
      labels:
        application: "{{ application }}"
        version: "{{ version }}"
        release: "{{ release }}"
        stage: production
      ## OPTIONAL: AWS IAM role (must be created separately via CF) to use
      # annotations:
      #   iam.amazonaws.com/role: "app-{{ application }}"
    spec:
      initContainers:
      - name: javaappagent
        image: pierone.stups.zalan.do/monitoring-appdynamics/javaappagent:latest
        volumeMounts:
        - name: agents-volume
          mountPath: /agents
        env:
          - name: APPDYNAMICS_AGENT_APPLICATION_NAME
            value: "monitoring-appdynamics"
      containers:
        - name: "{{ application }}"
          image: "pierone.stups.zalan.do/monitoring-appdynamics/java-simple-helloworld:{{ version }}"
          volumeMounts:
          - name: agents-volume
            mountPath: /agents
          - name: secrets
            mountPath: /etc/secrets
            readOnly: true
          env:
            # to include AppDynamics
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: APPDYNAMICS_ANALYTICS_URL
              value: http://$(NODE_NAME):9090/v1/sinks/bt            
            # for JVM applications:
            # set the maximum available memory as JVM would assume host/node capacity otherwise
            # this is evaluated by java-dynamic-memory-opts in the Zalando OpenJDK base image
            # see https://github.com/zalando/docker-openjdk
            - name: MEM_TOTAL_KB
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
                  divisor: 1Ki
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
            limits:
              memory: 200Mi
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
      volumes:
      - name: agents-volume
        emptyDir: {}
      - name: secrets
        secret:
          secretName: "appdynamics-test"
