apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    name: monitor
    application: appdynamics-machineagent
    version: "0.4"
  name: appdynamics-machineagent
  version: "0.4"
  namespace: kube-system
spec:
  selector:
    matchLabels:
      application: appdynamics-machineagent
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: appdynamics-machinenagent
      labels:
        application: appdynamics-machineagent
    spec:
      hostNetwork: true
      containers:
      - name: appdynamics-machineagent
        image: pierone.stups.zalan.do/monitoring-appdynamics/appdynamics-machine-agent-4.2:0.4
        volumeMounts:
        - name: appd-prod-secrets
          mountPath: /etc/secrets
        ports:
        - name: analytics-agent
          containerPort: 9090
          hostPort: 9090
        env:
          - name: APPDYNAMICS_AGENT_UNIQUE_HOST_ID
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
      volumes:
      - name: appd-prod-secrets
        secret:
          secretName: "appdynamics-prod"
